### ISSUE TITLE
XML format file for BCP import

### ISSUE THREAD

**Issue by MiroCillik** [keboola/db-writer-mssql#10]
XML format file could be better for escaping dst column names.
Here is an example with "double quote hack" also:
http://stackoverflow.com/questions/8530353/sql-bulk-insert-xml-format-file-with-double-quotes-in-terminator

**Comment by Halama** [comment]
@MiroCillik je to ještě aktuální?

**Comment by MiroCillik** [comment]
Ani nie, zavriem to
