### ISSUE TITLE
Heslo v error logu

### ISSUE THREAD

**Issue by padak** [keboola/db-writer-mssql#14]
Při timeoutu se zaloguje heslo (https://connection.keboola.com/admin/projects/2509/jobs/321616845?q=) + je timeout logovaný jako Internal Error.

PT: https://papertrailapp.com/groups/23635/events?q=docker-022684425f136a6117d962821e9f2ccb&focus=851457837514240020

**Comment by Halama** [comment]
docker runner už to hvězdičkuje
