### ISSUE TITLE
Use temporary table instead of normal

### ISSUE THREAD

**Issue by ujovlado** [keboola/db-writer-mssql#17]
There's an issue when user  (or credentials he has) has access only to one table. Since writer is creating "pseudo temporary" tables (normal tables with special name), writer fails with permissions issue.

Possible solution can be creation of temporary tables (prefix `#`)?

**Comment by ujovlado** [comment]
https://keboola.zendesk.com/agent/tickets/8199

**Comment by ujovlado** [comment]
This feature was turned off due some reason:
https://github.com/keboola/db-writer-mssql/commit/53f0230cd9830a4d88a25f68325e12e251711e1f

**Comment by ujovlado** [comment]
@MiroCillik neskusil by si to este preskumat? pomohlo by to vyriesit problem, co popisujem vyssie, t.j. ked ma user write prave len do specifickych tabuliek.

**Comment by ujovlado** [comment]
Tu som nasiel nieco k tomu, ze bcp nepodporuje local tmp tables (`#`) ale len global tmp tables (`##`).
https://technet.microsoft.com/en-us/library/ms191503(v=sql.105).aspx

**Comment by ErikZigo** [comment]
To je peklo pokud u writeru ma clovek povoleny zapis jen do nekterych tabulek :-)

**Comment by ujovlado** [comment]
Ked upravim kod, tak aby pouzival global tmp tables, tak sa mi rozbije z nejakeho dovodu kodovanie.

**Comment by ujovlado** [comment]
Global tmp tabulky som skusil takto:

```diff
diff --git a/src/Keboola/DbWriter/MSSQL/Application.php b/src/Keboola/DbWriter/MSSQL/Application.php
index c76f015..c9fdefb 100644
--- a/src/Keboola/DbWriter/MSSQL/Application.php
+++ b/src/Keboola/DbWriter/MSSQL/Application.php
@@ -28,7 +28,7 @@ class Application extends \Keboola\DbWriter\Application
 
         // write to staging table
         $stageTable = $tableConfig;
-        $stageTable['dbName'] = $writer->generateTmpName($tableConfig['dbName']);
+        $stageTable['dbName'] = '##' . $writer->generateTmpName($tableConfig['dbName']);
 
         $writer->drop($stageTable['dbName']);
         $writer->write($csv, $stageTable);
diff --git a/src/Keboola/DbWriter/Writer/MSSQL.php b/src/Keboola/DbWriter/Writer/MSSQL.php
index 520d609..9089528 100644
--- a/src/Keboola/DbWriter/Writer/MSSQL.php
+++ b/src/Keboola/DbWriter/Writer/MSSQL.php
@@ -95,7 +95,7 @@ class MSSQL extends Writer implements WriterInterface
 
         // create staging table
         $stagingTable = $table;
-        $stagingTable['dbName'] = $this->prefixTableName(uniqid('stage_') . '_', $dstTableName);
+        $stagingTable['dbName'] = $this->prefixTableName(uniqid('##stage_') . '_', ltrim($dstTableName, '#'));
         $this->drop($stagingTable['dbName']);
         $this->bcpCreateStage($stagingTable);
         $this->logger->info("BCP staging table created");
```

**Comment by ErikZigo** [comment]
Se vecer asi na to zkusim kouknout

**Comment by ujovlado** [comment]
Tak s tym pouzitim kodovania z db, do ktorej som pripojeny by to mohlo ficat.

**Comment by pocin** [comment]
caute kluci, nejaky update ohledne tohoto? Muzu kdyztak neco otestovat?

**Comment by padak** [comment]
Ahoj @pocin,
ty temp tabulky v mssql budeme ještě tak 2 týdny řešit. Čekáme na návrat @MiroCillik z dovolený. Jako workaround je, dostat práva na celé schema nebo vedle tabulky navíc na vytváření nových tabulek.
Padák

**Comment by ujovlado** [comment]
No ani moc nevyriesili ... chcel som pockat na teba, videl som v historii, ze si tam skusal tie temp tables (lokalne), no potom si to zavrhol (asi preto, ze ich nepodporuje ta bcp utilita) ... tak som chcel vediet preco. T.j. nech to nezacneme fixovat a ty potom za 5s povies "jasne, to nejde to som skusal" :)

**Comment by MiroCillik** [comment]
```
Global temporary tables and global temporary stored procedures are shared for all users’ sessions within the same Azure SQL database. User sessions from other Azure SQL databases cannot access global temporary tables. 
```

Takze pristup do tej `tempdb` je naviazany na pristup do nejakej `databaze` a maju k nej pristup len ti uzivatelia, ktori maju pristup do tej `databaze`. To mi pride celkom OK. Predsa len, mat pristup k jednej tabulke je "edge case".

@ujovlado jj, pamatam si, ze som to skusal, ale uz neviem presne, preco som to zavrhol :) A vsak pisete, ze s tymi global temp tables by to mohlo ist? Vyskusam to (znovu) :)

**Comment by MiroCillik** [comment]
BTW: Ten official PHP image (debian) tam nebol preto, ze v tej dobe ked som to robil, tak drivere pre najnovsi debian este neboli :) Ale to bola nejaka chyba na ich stranke / servery. Preto som tam dal to Ubuntu.

**Comment by ujovlado** [comment]
No mne sa zda, ze som ich tam tiez nevidel, len som nahodne skusil, ci tam nahodou nemaju aj priecinky pre debian 8 a mali ;)

**Comment by pocin** [comment]
cau kluci, pokrocilo to nejak? Uz me to tu zacina docela tlacit. Ma cenu zacit pracovat na tech workaroundech s pravy nebo je reseni v dohlednu?

**Comment by MiroCillik** [comment]
@pocin prepac, celkom som sa tu zasekal s cistenim a updatovanim tohto repozitara a fixovanim mensich bugov, takze k samotnemu problemu som sa zatial ani nedostal :/ Dnes uz ale s touto "cistkou" koncim a pustim sa do toho. Povedal by som, ze ries paralelne workaroundy s pravami, pre istotu :) Zajtra ti budem vediet povedat viac.

**Comment by MiroCillik** [comment]
@pocin Zda sa, ze to pojde :) Cakam na review PR, potom to nasadim a mozeme to vyskusat u klienta.

**Comment by MiroCillik** [comment]
@pocin pocuj, sorry za predcasne nadeje :( Nakoniec sme tu o tom este debatovali, ale dosli sme k tomu, ze je to z hladiska bebzpecnosti asi neakceptovatelne.. Lebo do tych globalnych temp tabuliek vidia uplne vsetci uzivatelia. Takze ak napriklad nejaky uzivatel ma pristup len k jednej tabulke a do nejakych inych tabuliek sa nalievaju data cez tie globalne temp tabulky. Tak v tej tempdb by mohol vidiet obsah tychto tabuliek, z coho by klient v konecnom dosledku asi radost nemal :(

**Comment by MiroCillik** [comment]
Lokal temp tables nejdu pouzit z toho dovodu, ze writer sa do DB pripaja dvomi sposobmi. Cez PDO a cez BCP. Cez PDO sa tabulky vytvoria a cez BCP sa do nich nahravaju data. Ked cez PDO vytvorim lokalnu temp tabulku, je viazanu na to spojenie, BCP ju potom nevidi :(

Ta stage tabulka je vzdy viazana na nejaku schemu a databazu. Co tie global temp tabulky nie su. Takze si predstav, ze na nejakom servery mozu lezat databaze uplne nesuvisiacich "aplikacii". Ale do tej tempdb vidia vsetci. Takze preto su tie stavajuce stage tabulky lepsie ako tie global temp.

Izolovane prostredie pre writer je idealne schema alebo databaza v podstate tak ako pises. S tym aliasom mi to pride dobry napad. A bude to aj prehladne a jasne. A tie prava budu jednoduche.
Takto mi to pride najlepsie. 

Je totiz pravda, ze ten writer potrebuje delete prava pre tu schemu/databazu, kedze za sebou potrebuje mazat tie stageing tabulky. Coho sa klient moze obavat, ze mu to zmaze jeho tabulky, aj ked je to nepravdepodobne.
