### ISSUE TITLE
Cannot import large data (text, etc.)

### ISSUE THREAD

**Issue by ErikZigo** [keboola/db-writer-mssql#35]
Staging tabulka pro `bcp` vytvari sloupce `VARCHAR(255)`, diky tomu import tabluky skonci chybou kdyz v zdrojove tabulce jsou vetsi data.

![image](https://user-images.githubusercontent.com/1726727/43015301-9560d1c2-8c4f-11e8-84a9-ca1b23cd1c18.png)

**Comment by MiroCillik** [comment]
Aha, mas pravdu, ked je to text tak to nastavi default dlzku 255. 
https://github.com/keboola/db-writer-mssql/blob/master/src/Writer/MSSQL.php#L73
Opravim to.
