### ISSUE TITLE
Exponential retries

### ISSUE THREAD

**Issue by ujovlado** [keboola/db-writer-mssql#41]
Currently, there are 3 retries, each after 1s, which is pointless.

![Screenshot_2019-09-05_21-10-37](https://user-images.githubusercontent.com/419849/64371864-e66e5780-d021-11e9-8ccb-d44ce13145fa.png)

**Comment by MiroCillik** [comment]
There is exponential backoff, but it only has 3 tries. I will increment that and maybe start from base 1 instead of 0. 
https://github.com/keboola/db-writer-mssql/blob/master/src/Writer/MSSQL.php#L378
